version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: finifications-db
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata_finifications:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-prod
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
      
  daily-email-job:
    image: node:20-alpine
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["/bin/sh", "-c"]
    command: |
      echo "0 17 * * * cd /app && node server/jobs/emailJob.js" > /etc/crontabs/root \
      && crond -f -l 8

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: finifications-server
    restart: always
    env_file:
      - ./.env        # root env file
      - ./server/.env # server-specific env file (overrides root if duplicate)
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: sh -c "node prisma-wait.js && npx prisma migrate deploy && npm start"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: finifications-client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  pgdata_finifications:
  redisdata:

# Yessir
